name: NodeJS CI Test

# Events
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs per runner
jobs:
  build:
    # Scelta della piattaforma
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Usando Node.js in versione ${{ matrix.node-version }}
        uses: actions/setup-node@v2  # Aggiornato a v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test

  docker-build-and-push:  # Corretto il nome del job
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2

      - name: Login a Docker Hub
        uses: docker/login-action@v2  # Aggiornato a v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3  # Aggiornato a v3
        with:
          context: .
          file: Dockerfile  # Assicurati che il nome sia corretto
          push: true
          tags: zapp75/gestione_libri-api:latest  # Aggiunto :latest per la versione dell'immagine
